deploy:
  file: './enrich/environment_definition/test1/environment_definition.def'
  repo: 'DNI-New-Platform/fusion_enriched_site_definition'

api:
  passkey: '<yourGithubApiToken>'
  username: '<yourGitHubUsername>'
  build_url: 'https://devbuild.dnitv.net'

repositories:
  fusion-api-epg: 'epg_dnitv_com'
  fusion-api-device: 'internal_mobile_apps_fusion'
  fusion-site-www-dplay-dk: 'www_dplay_dk'
  fusion-site-www-dplay-se: 'www_dplay_se'
  fusion-site-www-dplay-no: 'www_dplay_no'
  fusion-api-dummy: 'none'